### ISSUE TITLE
plugin for x64dbg?

### ISSUE THREAD

**Issue by aaaddress1** [airbus-cert/Yagi#2]
hi there, thanks for the nice job!
is there any possible to support Yagi for x64dbg? it's useful.
although x64dbg embedded a decompiler Snowman, however it's totally not working :(

![image](https://user-images.githubusercontent.com/8559056/132618902-45d11eb7-d967-4d09-a7a2-ed53435c8ad3.png)

**Comment by citronneur** [comment]
Hi @aaaddress1 ,

Sorry It's part of another project i think.

Have a nice day,

Sylvain
