### ISSUE TITLE
avr8 decompiler

### ISSUE THREAD

**Issue by lukaskuzmiak** [airbus-cert/Yagi#4]
I saw you guys mentioned it might not be that hard to add another decompiler. Ghidra does have support for AVR8 (in particular I'm interested in the Xmega stuff). Is this somewhere in your pipeline? Thanks!

**Comment by citronneur** [comment]
The work is done but avr8 is a nightmare with a lot of kind of processor. All are not supported by ghidra. I hope you will enjoy.
Have a nice day!
