### ISSUE TITLE
Crashes "ida.exe"

### ISSUE THREAD

**Issue by BigJim** [airbus-cert/Yagi#7]
Tried running Yagi for IDA 7.6. 64 bit runs fine, but the 32bit target "ida.exe" will crash almost instantly, and without any sort of dialog/warning box.

Consider wrapping your IDA "run" in an a C or C++ exception handler.
It's what I do, great for development. With a `msg()` in the handler it will tell me my plugin crashed instead of crashing IDA (most of the time anyhow, could cause IDA to crash outside of our plugin space et al).

**Comment by citronneur** [comment]
Hello @BigJim !

Thanks for your feedback!
I didn't achieved to reproduce your crach. I've already have a big try cash for almost every internal exceptions for yagi [here](https://github.com/airbus-cert/Yagi/blob/a4528c83dff7f87c804140727b06e0359aca1d99/yagi/src/ghidradecompiler.cc#L184).

Could you please be more precise ?

Have a nice day,
Sylvain

**Comment by BigJim** [comment]
I actually got some small .idb to run without crashing.  But then other larger ones crash IDA every time.
Sorry, I can't upload those.

I see in the Ghidra source:
`struct LowlevelError {
  string explain;		///< Explanatory string
  /// Initialize the error with an explanatory string
  LowlevelError(const string &s) { explain = s; }
};`

Are you sure that error handler catches low level exceptions like access violations?
Seems like I had to use a [_set_se_translator](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/set-se-translator?view=msvc-160&viewFallbackFrom=vs-2019).

Easy enough to test. At the top of your try/catch statement do a `*((PBYTE) 0) = 1;` to case an access violation.
See if the handler catches it or not.

**Comment by citronneur** [comment]
No you are right, access violation, for example, are not handle. But most of the time it's come from IDA or Ghidra, and I prefer to end the process if an access violation happened.

LowLevelError is the name of Ghidra's exceptions.

**Comment by BigJim** [comment]
I doubt your typical IDA user prefers this behavior.

Should an add-on/plugin exit IDA when it fails?  What if the user didn't do a save recently?

With the low level handler you can catch the most common crash (access violation) without having to exit.
You can have in that handler something like:
`msg("\n*** Yagi: SE exception: Type: 0x%08X @ Address: 0x%llX! ***\n", ExceptionCode, (UINT64) pExceptionInfo->ExceptionRecord->ExceptionAddress);`
And then you probably don't need to exit. Maybe some memory leaks (unless you have free's in the handler), etc., but IMHO better than just crashing out.

**Comment by citronneur** [comment]
I finnaly manage to reproduce a crash due to an infinite recursive loop in type solve algorithm. I will try to produce a release before end of the week!

**Comment by citronneur** [comment]
This is due to cyclic reference in type tree...
